[tool.black]
line-length = 88
target-version = ['py310']
skip-magic-trailing-comma = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.venv
    | __pycache__
    | \.mypy_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
known_first_party = ["Module_30_homework"]

[tool.flake8]
max-line-length = 88
max-complexity = 18
ignore = "E203, W503, PIE798"
exclude = ".git,.venv,__pycache__,*/migrations/*"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.mypy]
pythonpath = "src"
namespace_packages = true
ignore_missing_imports = true
disallow_untyped_defs = true

