[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.venv
    | __pycache__
    | \.mypy_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 88
force_sort_within_sections = true
known_first_party = ["Module_30_homework"]

[tool.flake8]
max-line-length = 88
max-complexity = 18
ignore = "E203, W503, PIE798"
exclude = ".git,.venv,__pycache__,*/migrations/*"