on:
  push:
    branches: [ "*" ] 
  pull_request:
    branches: [ "main" ]
    
jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.12.0 "black[isort]" flake8==4.0.1 flake8-bugbear==22.1.11 \
          flake8-pie==0.15.0 isort==5.9.3 mypy==0.931 pytest==7.0.1

      - name: Run formatting checks
        run: |
          isort --check src/ tests/ app.py
          black --check src/ tests/ app.py

      - name: Run flake8
        run: flake8 --max-line-length=88 --ignore=E203,W503,PIE798 app.py /src

      - name: Run mypy
        run: |
          mypy --ignore-missing-imports \
               --disallow-untyped-defs \
               src/ tests/ app.py

      - name: Run tests
        run: |
          pytest tests/ -v    
