on:
  push:
    branches: [ "*" ] 
  pull_request:
    branches: [ "main" ]
    
jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade \
          black==23.12.0 \
          "black[isort]" \
          importlib-metadata==6.8.0 \
          flake8-bugbear==22.1.11 \
          flake8-pie==0.15.0 \
          isort==5.12.0 \
          mypy==1.6.1 \
          pytest==7.4.3

      - name: Run formatting checks
        run: |
          isort --check src/ tests/
          black --check src/ tests/

      - name: Run flake8
        run: flake8 --max-line-length=88 --ignore=E203,W503,PIE798 src/

      - name: Run mypy
        run: |
          mypy src/ tests/

      - name: Run tests
        run: |
          PYTHONPATH=src:. pytest tests/ -v
